apiVersion: v1
kind: Service
metadata:
  name: v2ray-okteto
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "v2ray-okteto"
    port: 443
  selector:
    app: v2ray-okteto
